export const SHOW_MENU = 'menu/SHOW_MENU'
export const HIDE_MENU = 'menu/HIDE_MENU'
// export const SET_TOKEN = 'token/SET_TOKEN'
// export const SET_USER_ID = 'user/SET_USER_ID'
// export const SET_IDENTITY_INFO = 'identity/SET_IDENTITY_INFO'
